### ISSUE TITLE
why the storage is related to a client and not to the whole zope instance?

### ISSUE THREAD

**Issue by simahawk** [collective/collective.jbot#5]
maybe this is a silly question but I don't get why you need to store customized contents into `<buildout-dir>/var/instance/jbot.` instead of `<buildout-dir>/var/jbot`. The latter path will be easier to mantain I think.

**Comment by vangheem** [comment]
All you have access to is Globals.data_dir. There is no concept of <buildout-dir> once a plone instance is running.

**Comment by simahawk** [comment]
If I remember right `Globals.ZOPE_HOME` leads you to the root of the buildout.
Also, if `data_dir` points always to var/instance you can always split the last bit ;)

**Comment by vangheem** [comment]
That's assuming people always structure their buildout the same.

If you get <buildout-dir> correctly from ZOPE_HOME, you are assuming people have a /var directory setup with the correct permissions.

We can always assume, I think, that data_dir is writable since that is where logs are written to.

**Comment by simahawk** [comment]
I guess so :)
We can build the path like: `os.path.join('/'.join(Globals.data_dir.split('/)[:-1]), 'jbot')`
and we can always check it the path is writeable and if not just log an error without breaking anything.

**Comment by vangheem** [comment]
sure. PR welcome :)

**Comment by simahawk** [comment]
sure :) I need to play a little bit w/ this and maybe include it into the theming training at the ploneconf ;)
